services:
  api:
    build: ./api
    container_name: earthquake_monitor_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  test:
    build: ./api
    container_name: test_runner
    command: [ "python", "manage.py", "test", "--noinput" ]
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: earthquake_monitor_frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: earthquake_monitor_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  db_data:
