# Generated by Django 4.2 on 2024-12-31 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.CreateModel(
            name="EarthquakeSearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("raw_earthquake_data", models.JSONField(blank=True, default=dict)),
                (
                    "nearest_earthquake_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nearest_earthquake_magnitude",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "nearest_earthquake_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="earthquake.city",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="earthquakesearchresult",
            index=models.Index(
                fields=["city", "start_date", "end_date"],
                name="earthquake__city_id_0d0220_idx",
            ),
        ),
    ]
