[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
profile = "black"
line_length = 88

[tool.flake8]
max-line-length = 88
extend-ignore = ['E203', 'E266', 'E501', 'W503', 'F403', 'F401']
