line-length = 120
indent-width = 4


exclude = [
    ".tox",
    ".git",
    "migrations",
    "settings",
    "*/static/CACHE/*",
    "docs",
    "node_modules",
]

[lint]
select = [
    # pycodestyle
    "E",
    # pyflakes
    "F",
    # flake8-bugbear
    # "B",
    # isort
    "I"
]

[lint.isort]
known-first-party = ["api"]
default-section = "third-party"


[format]
line-ending = "lf"
indent-style = "space"
